Repository Aparking/AparKing_Backend, pull requests merged in 2024-04, with the labels that each got.

#182 fix: actions Codacy analisis
  .github/workflows/django.yml
Labels: fix, conf, g1

#213 implementación de pasarela de pago para membresía
  AparKing_Backend/settings.py
  AparKing_Backend/urls.py
  Populate.json
  actionsRequirements.txt
  apps/authentication/models.py
  apps/authentication/views.py
  apps/parking/enums.py
  apps/payment/enums.py
  apps/payment/models.py
  apps/payment/urls.py
  apps/payment/views.py
  docker/migrationsInit.sh
  requirements.txt
Labels: feat, g1

#214 Datos de usuario de backend a frontend
  apps/authentication/serializers.py
  apps/authentication/urls.py
  apps/authentication/views.py
  apps/garagement/tests/test_urls.py
  apps/garagement/tests/test_views.py
Labels: fix, feat

#221 fix: resolve bun in populate file
  Populate.json
Labels: fix, g1

#222 Hotfix/populate.json/220
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/epic-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/test-template.md
  Populate.json
Labels: fix, g1

#216 Gestión de alquiler de garaje
  .gitignore
  AparKing_Backend/settings.py
  AparKing_Backend/urls.py
  actionsRequirements.txt
  apps/authentication/serializers.py
  apps/authentication/urls.py
  apps/authentication/views.py
  apps/booking/serializers.py
  apps/booking/urls.py
  apps/booking/validations.py
  apps/booking/views.py
  apps/garagement/serializers.py
  apps/garagement/tests/test_urls.py
  apps/garagement/tests/test_views.py
  apps/garagement/urls.py
  apps/garagement/validations.py
  apps/garagement/views.py
Labels: feat

#227 Arreglo de bugs de validación para las reviews y bookings
  apps/booking/models.py
  apps/booking/serializers.py
  apps/booking/views.py
Labels: fix

#228 Test: Listado de anuncios de alquiler por el administrador
  apps/garagement/tests/test_views.py
Labels: test, g3

#229 Test: Listado y filtrado de alquileres
  apps/garagement/tests/test_views.py
Labels: test, g3

#230 Tests: Añadir comentarios en una reserva
  apps/booking/serializers.py
  apps/booking/tests.py
  apps/booking/urls.py
  apps/booking/views.py
  apps/garagement/tests/test_urls.py
  apps/garagement/tests/test_views.py
Labels: test

#233 fix-login/register/#231
  apps/parking/views.py
Labels: fix

#232 Fix login/register/#231
  .github/workflows/django.yml
  apps/parking/views.py
Labels: fix, g1

#234 Search Location
  apps/parking/urls.py
  apps/parking/views.py
Labels: feat, g1

#241 Feat/search locations/16
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/epic-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/test-template.md
  .github/workflows/django.yml
  .gitignore
  AparKing_Backend/settings.py
  AparKing_Backend/urls.py
  Populate.json
  actionsRequirements.txt
  apps/authentication/models.py
  apps/authentication/serializers.py
  apps/authentication/urls.py
  apps/authentication/views.py
  apps/booking/models.py
  apps/booking/serializers.py
  apps/booking/tests.py
  apps/booking/urls.py
  apps/booking/validations.py
  apps/booking/views.py
  apps/garagement/serializers.py
  apps/garagement/tests/test_urls.py
  apps/garagement/tests/test_views.py
  apps/garagement/urls.py
  apps/garagement/validations.py
  apps/garagement/views.py
  apps/mailer/__init__.py
  apps/mailer/admin.py
  apps/mailer/apps.py
  apps/mailer/email_backend.py
  apps/mailer/forms.py
  apps/mailer/generic_sender.py
  apps/mailer/migrations/__init__.py
  apps/mailer/models.py
  apps/mailer/templates/mailer/email_form_page.html
  apps/mailer/tests.py
  apps/mailer/urls.py
  apps/mailer/views.py
  apps/parking/filters.py
  apps/parking/serializers.py
  apps/parking/urls.py
  apps/parking/views.py
  apps/utils/code_generator.py
  requirements.txt
Labels: feat

#242 Epic/paking management/14
  apps/parking/serializers.py
  apps/parking/urls.py
  apps/parking/views.py
Labels: epic

#244 feat: funcionalidad registro de vehiculo #240
  apps/authentication/models.py
  apps/authentication/serializers.py
  apps/authentication/urls.py
  apps/authentication/views.py
Labels: feat, g1

#285 Arreglar cesión de plazas de aparcamiento #255
  apps/authentication/views.py
  apps/parking/urls.py
  apps/parking/views.py
Labels: fix, g1

#290 Fix selección método pago en reserva #261
  apps/booking/enums.py
  apps/booking/models.py
  apps/booking/urls.py
  apps/booking/views.py
  apps/garagement/views.py
Labels: fix, g1
