Repository Aparking/AparKing_Backend, pull requests merged in 2024-05, with the labels that each got.

#294 feat: funcioalidad para añadir fecha y hora a la cesion de aparcamiento
  apps/authentication/models.py
  apps/parking/models.py
  apps/parking/serializers.py
  apps/parking/views.py
  apps/payment/models.py
  apps/payment/views.py
Labels: feat, g1

#314 feat: compra de créditos
  apps/authentication/models.py
  apps/payment/models.py
  apps/payment/urls.py
  apps/payment/views.py
Labels: feat, g1

#318 Fix/cesiones y listado vehiculos con eleccion vehiculo/312
  apps/authentication/models.py
  apps/authentication/urls.py
  apps/authentication/views.py
  apps/parking/models.py
  apps/parking/views.py
  apps/payment/views.py
Labels: feat, g1

#323 Develop
  Populate.json
  apps/authentication/models.py
  apps/authentication/urls.py
  apps/authentication/views.py
  apps/booking/enums.py
  apps/booking/models.py
  apps/booking/urls.py
  apps/booking/views.py
  apps/garagement/views.py
  apps/parking/enums.py
  apps/parking/models.py
  apps/parking/serializers.py
  apps/parking/urls.py
  apps/parking/views.py
  apps/payment/models.py
  apps/payment/urls.py
  apps/payment/views.py
Labels: deploy, g1

#327 fix: populate.json
  Populate.json
  docker/migrationsInit.sh
Labels: fix, g1

#328 Develop
  Populate.json
  apps/authentication/models.py
  apps/authentication/serializers.py
  apps/authentication/urls.py
  apps/authentication/views.py
  docker/migrationsInit.sh
Labels: deploy

#348 fix: estado de las cesiones en el mapa
  Populate.json
  apps/parking/views.py
Labels: fix, g1

#349 Fix validate vehicle form
  apps/authentication/serializers.py
  apps/parking/serializers.py
Labels: fix, g1

#351 Feat/add edit delete users by admin/4
  apps/authentication/models.py
  apps/authentication/serializers.py
  apps/authentication/tests/tests.py
  apps/authentication/urls.py
  apps/authentication/views.py
Labels: test, g3

#359 Test/views payment/356
  apps/payment/tests.py
  apps/payment/urls.py
  apps/payment/views.py
Labels: test, g1

#366 Fix: Check booking before deleting user
  apps/booking/urls.py
  apps/booking/views.py
Labels: fix, g3
