Repository Aparking/AparKing_Backend, pull requests merged in 2024-03, with the labels that each got.

#68 fix: Register, Login and Logout Closes #58
  .gitignore
  AparKing_Backend/settings.py
  AparKing_Backend/urls.py
  README.md
  apps/authentication/admin.py
  apps/authentication/backends.py
  apps/authentication/enums.py
  apps/authentication/forms.py
  apps/authentication/migrations/__init__.py
  apps/authentication/models.py
  apps/authentication/serializers.py
  apps/authentication/tests.py
  apps/authentication/tests/__init__.py
  apps/authentication/tests/tests.py
  apps/authentication/urls.py
  apps/authentication/views.py
  apps/booking/migrations/__init__.py
  apps/booking/serializers.py
  apps/garagement/migrations/__init__.py
  apps/garagement/serializers.py
  apps/parking/migrations/__init__.py
  apps/parking/serializers.py
  apps/payment/migrations/__init__.py
  apps/payment/serializers.py
  requirements.txt
Labels: fix

#69 Feat/create model
  apps/authentication/models.py
  apps/booking/enums.py
  apps/booking/models.py
  apps/garagement/enums.py
  apps/garagement/models.py
  apps/parking/enums.py
  apps/parking/models.py
  apps/payment/enums.py
  apps/payment/models.py
  requirements.txt
Labels: feat, g1

#72 Listado de alquileres de garajes
  .github/workflows/django.yml
  .gitignore
  AparKing_Backend/settings.py
  AparKing_Backend/urls.py
  README.md
  apps/authentication/admin.py
  apps/authentication/backends.py
  apps/authentication/enums.py
  apps/authentication/forms.py
  apps/authentication/migrations/__init__.py
  apps/authentication/models.py
  apps/authentication/serializers.py
  apps/authentication/tests.py
  apps/authentication/tests/__init__.py
  apps/authentication/tests/tests.py
  apps/authentication/urls.py
  apps/authentication/views.py
  apps/booking/enums.py
  apps/booking/migrations/__init__.py
  apps/booking/models.py
  apps/booking/serializers.py
  apps/garagement/enums.py
  apps/garagement/migrations/__init__.py
  apps/garagement/models.py
  apps/garagement/serializers.py
  apps/garagement/urls.py
  apps/garagement/views.py
  apps/parking/enums.py
  apps/parking/migrations/__init__.py
  apps/parking/models.py
  apps/parking/serializers.py
  apps/payment/enums.py
  apps/payment/migrations/__init__.py
  apps/payment/models.py
  apps/payment/serializers.py
  info.yml
  requirements.txt
Labels: feat, g3

#73 Creación de un anuncio de garaje
  apps/garagement/serializers.py
Labels: feat, g3

#74 Editar y eliminar alquiler de parking
  apps/garagement/permissions.py
  apps/garagement/serializers.py
  apps/garagement/urls.py
  apps/garagement/validations.py
  apps/garagement/views.py
Labels: feat, g3

#98 Mejora en la Configuración Inicial de Docker para Contenedores
  Dockerfile.dev
  apps/parking/views.py
  docker-compose.yml
Labels: conf

#99 Mejora en la Configuración Inicial de Docker para Contenedores
  Dockerfile.dev
  apps/parking/views.py
  docker-compose.yml
Labels: conf, deploy

#106 Feat/complete map implementation for parking zones/103
  apps/parking/consumers.py
  apps/parking/enums.py
  apps/parking/filters.py
  apps/parking/models.py
  apps/parking/templates/parking/room.html
  apps/parking/tests.py
  apps/parking/urls.py
  apps/parking/views.py
Labels: feat, g1

#111 Añadir, editar y eliminar usuarios desde admin [Backend]
  AparKing_Backend/settings.py
  apps/authentication/urls.py
  apps/authentication/views.py
Labels: feat, g2

#114 fix: populate.json delete parking entity and messages atribute #113
  Populate.json
Labels: fix, g1

#127 Update issue templates
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/epic-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/test-template.md
Labels: refactor, conf

#107 Feat/pricings plans and permits/36
  AparKing_Backend/urls.py
  apps/authentication/serializers.py
  apps/authentication/tests/tests.py
  apps/authentication/urls.py
  apps/authentication/views.py
  apps/payment/admin.py
  apps/payment/models.py
  apps/payment/serializers.py
  apps/payment/tests.py
  apps/payment/urls.py
  apps/payment/views.py
  requirements.txt
Labels: feat, g1

#146 Creación de garajes e imagenes asociadas #Backend
  AparKing_Backend/settings.py
  apps/garagement/serializers.py
  apps/garagement/views.py
Labels: feat

#156 Conf: Arreglo de la configuración del despliegue
  AparKing_Backend/settings.py
  Dockerfile
  Dockerfile.dev
  apps/__init__.py
  deploy.md
  docker-compose.yml
  docker/backend.Dockerfile
  docker/backendInit.sh
  docker/migrations.Dockerfile
  docker/migrationsInit.sh
  entrypoint-wrapper.sh
  env/backend.env
  env/database.env
  importCSV.py
Labels: conf, deploy

#109 Epic/paking management/14
  apps/parking/consumers.py
  apps/parking/enums.py
  apps/parking/filters.py
  apps/parking/models.py
  apps/parking/templates/parking/room.html
  apps/parking/tests.py
  apps/parking/urls.py
  apps/parking/views.py
Labels: feat, g1

#158 Modificación del backend: añadido Creación de garajes con asociación de imágenes + listado
  apps/garagement/models.py
  apps/garagement/serializers.py
  apps/garagement/urls.py
  apps/garagement/views.py
Labels: feat, g3

#161 Refactor: Agregado el listado y filtrado de garajes.
  AparKing_Backend/settings.py
  AparKing_Backend/urls.py
  apps/garagement/models.py
  apps/garagement/permissions.py
  apps/garagement/serializers.py
  apps/garagement/tests/__init__.py
  apps/garagement/tests/test_models.py
  apps/garagement/tests/test_serializers.py
  apps/garagement/tests/test_urls.py
  apps/garagement/tests/test_views.py
  apps/garagement/urls.py
  apps/garagement/validations.py
  apps/garagement/views.py
  images/test_image.jpg
Labels: refactor, g3

#168 Fix: docker, test, requirements
  actionsRequirements.txt
  apps/garagement/tests/tests.py
  apps/parking/forms.py
  apps/parking/models.py
  apps/parking/tests.py
  apps/parking/urls.py
  apps/parking/views.py
  entrypoint-wrapper.sh
  requirements.txt
Labels: fix, g1

#167 feat: double factor implemented and logout #164
  .gitignore
  AparKing_Backend/settings.py
  actionsRequirements.txt
  apps/authentication/models.py
  apps/authentication/urls.py
  apps/authentication/views.py
  apps/mailer/__init__.py
  apps/mailer/admin.py
  apps/mailer/apps.py
  apps/mailer/email_backend.py
  apps/mailer/forms.py
  apps/mailer/generic_sender.py
  apps/mailer/migrations/__init__.py
  apps/mailer/models.py
  apps/mailer/templates/mailer/email_form_page.html
  apps/mailer/tests.py
  apps/mailer/urls.py
  apps/mailer/views.py
  apps/utils/code_generator.py
  requirements.txt
Labels: feat, g1

#173 Edición y borrado de un anuncio de alquiler de garaje
  .gitignore
  AparKing_Backend/settings.py
  AparKing_Backend/urls.py
  actionsRequirements.txt
  apps/authentication/models.py
  apps/authentication/urls.py
  apps/authentication/views.py
  apps/garagement/serializers.py
  apps/garagement/tests/tests.py
  apps/garagement/urls.py
  apps/garagement/validations.py
  apps/garagement/views.py
  apps/mailer/__init__.py
  apps/mailer/admin.py
  apps/mailer/apps.py
  apps/mailer/email_backend.py
  apps/mailer/forms.py
  apps/mailer/generic_sender.py
  apps/mailer/migrations/__init__.py
  apps/mailer/models.py
  apps/mailer/templates/mailer/email_form_page.html
  apps/mailer/tests.py
  apps/mailer/urls.py
  apps/mailer/views.py
  apps/parking/forms.py
  apps/parking/models.py
  apps/parking/tests.py
  apps/parking/urls.py
  apps/parking/views.py
  apps/utils/code_generator.py
  entrypoint-wrapper.sh
  requirements.txt
Labels: feat, g3

#179 Gestión de reservas de garajes.
  apps/booking/serializers.py
  apps/booking/validations.py
  apps/booking/views.py
  apps/garagement/urls.py
Labels: feat, epic
